[package]
name = "sh2-as"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "7.4.0"
pest = "2.7.15"
pest_derive = "2.7.15"
test-log = { version = "0.2.17", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
